---
- name: Update Environments
  # Do not prevent provision when database is unavailable
  ignore_errors: "{{ gpte_reporting_ignore_errors | bool }}"
  mysql_query:
    login_db: "{{ gpte_db.mysql_db }}"
    login_host: "{{ gpte_db.mysql_host }}"
    login_port: "{{ gpte_db.mysql_port }}"
    login_password: "{{ gpte_db.mysql_password }}"
    login_user: "{{ gpte_db.mysql_user }}"

    positional_args:
    - "{{ gpte_reporting_uuid }}"
    - "{{ gpte_reporting_guid }}"
    - "{{ vars.anarchy_subject.spec.governor }}"
    - "{{ gpte_reporting_env_type }}"
    - "{{ gpte_reporting_cloud_provider }}"
    - "{{ gpte_reporting_cloud_region }}"
    - "{{ gpte_reporting_user_name }}"
    - "{{ gpte_reporting_user_email }}"
    - "{{ gpte_reporting_job_vars | to_json }}"
    - "{{ gpte_reporting_user_name }}"
    - "{{ gpte_reporting_user_email }}"
    query:
    - >-
      INSERT INTO Environments (
        `UUID`,
        `GUID`,
        `AnarchyGovernor`,
        `EnvironmentType`,
        `CloudProvider`,
        `CloudRegion`,
        `UserName`,
        `UserEmail`,
        `ProvisionVars`,
        `State`,
        `ProvisionCompleteDateTime`
      ) VALUES (
        %s, %s, %s, %s, %s, %s, %s, %s, %s,
        'started', NOW()
      ) ON DUPLICATE KEY UPDATE
      `UserName` = %s,
      `UserEmail` = %s,
      `State` = 'started',
      `ProvisionCompleteDateTime` = NOW()

- name: Update EnvironmentRuntimes
  # Do not prevent provision when database is unavailable
  ignore_errors: "{{ gpte_reporting_ignore_errors | bool }}"
  mysql_query:
    login_db: "{{ gpte_db.mysql_db }}"
    login_host: "{{ gpte_db.mysql_host }}"
    login_port: "{{ gpte_db.mysql_port }}"
    login_password: "{{ gpte_db.mysql_password }}"
    login_user: "{{ gpte_db.mysql_user }}"

    positional_args:
    - "{{ gpte_reporting_uuid }}"
    query:
    - >-
      INSERT INTO EnvironmentRuntimes (`UUID`) VALUES (%s)
