---
- name: Update Environments record {{ gpte_reporting_uuid }} to state stopped
  # Do not prevent provision when database is unavailable
  ignore_errors: "{{ gpte_reporting_ignore_errors | bool }}"
  mysql_query:
    login_db: "{{ gpte_db.mysql_db }}"
    login_host: "{{ gpte_db.mysql_host }}"
    login_port: "{{ gpte_db.mysql_port }}"
    login_password: "{{ gpte_db.mysql_password }}"
    login_user: "{{ gpte_db.mysql_user }}"

    positional_args:
    # INSERT
    - "{{ gpte_reporting_uuid }}"
    - "{{ gpte_reporting_guid }}"
    - "{{ vars.anarchy_subject.spec.governor }}"
    - "{{ gpte_reporting_env_type }}"
    - "{{ gpte_reporting_cloud_provider }}"
    - "{{ gpte_reporting_cloud_region }}"
    - "{{ request_guid }}"
    - "{{ request_guid }}" # RequestDateTime - set to UTC_TIMESTAMP() if not emptystring
    - "{{ gpte_reporting_user_name }}"
    - "{{ gpte_reporting_user_email }}"
    - "{{ gpte_reporting_job_vars | to_json }}"
    # ON DUPLICATE KEY UPDATE
    - "{{ request_guid }}"
    - "{{ request_guid }}" # RequestDateTime - set to UTC_TIMESTAMP() if not emptystring
    - "{{ gpte_reporting_user_name }}"
    - "{{ gpte_reporting_user_email }}"
    query:
    - |
      INSERT INTO Environments SET
        `UUID` = %s,
        `GUID` = %s,
        `AnarchyGovernor` = %s,
        `EnvironmentType` = %s,
        `CloudProvider` = %s,
        `CloudRegion` = NULLIF(%s, ''),
        `RequestGUID` = NULLIF(%s, ''),
        `RequestDateTime` = IF(%s = '', NULL, UTC_TIMESTAMP()),
        `UserName` = NULLIF(%s, ''),
        `UserEmail` = NULLIF(%s, ''),
        `ProvisionVars` = %s,
        `State` = 'stopped'
      ON DUPLICATE KEY UPDATE
        `RequestGUID` = IFNULL(`RequestGUID`, NULLIF(%s, '')),
        `RequestDateTime` = IFNULL(`RequestDateTime`, IF(%s = '', NULL, UTC_TIMESTAMP())),
        `UserName` = IFNULL(`UserName`, NULLIF(%s, '')),
        `UserEmail` = IFNULL(`UserEmail`, NULLIF(%s, '')),
        `State` = 'stopped'

- name: Set StopDateTime in EnvironmentRuntimes for {{ gpte_reporting_uuid }} on stop complete
  # Do not prevent provision when database is unavailable
  ignore_errors: "{{ gpte_reporting_ignore_errors | bool }}"
  mysql_query:
    login_db: "{{ gpte_db.mysql_db }}"
    login_host: "{{ gpte_db.mysql_host }}"
    login_port: "{{ gpte_db.mysql_port }}"
    login_password: "{{ gpte_db.mysql_password }}"
    login_user: "{{ gpte_db.mysql_user }}"

    positional_args:
    - "{{ gpte_reporting_uuid }}"
    query:
    - >-
      UPDATE EnvironmentRuntimes
      SET StopDateTime=UTC_TIMESTAMP()
      WHERE `UUID` = %s AND StopDateTime IS NULL
