---
- name: Insert info in GPTE Cost Reporting DB
  # Do not prevent provision when database is unavailable
  ignore_errors: "{{ gpte_reporting.ignore_errors | bool }}"
  mysql_query:
    login_db: "{{ gpte_reporting.mysql_db }}"
    login_host: "{{ gpte_reporting.mysql_host }}"
    login_port: "{{ gpte_reporting.mysql_port }}"
    login_password: "{{ gpte_reporting.mysql_password }}"
    login_user: "{{ gpte_reporting.mysql_user }}"

    positional_args:
    - "{{ gpte_reporting.uuid }}"
    - "{{ gpte_reporting.guid }}"
    - "{{ vars.anarchy_subject.spec.governor }}"
    - "{{ gpte_reporting.env_type }}"
    - "{{ gpte_reporting.cloud_provider }}"
    - "{{ gpte_reporting.cloud_region }}"
    - "{{ gpte_reporting.user_name }}"
    - "{{ gpte_reporting.user_email }}"
    - "{{ job_vars | to_json }}"
    - "{{ gpte_reporting.user_name }}"
    - "{{ gpte_reporting.user_email }}"
    query:
    - >-
      INSERT INTO Provisions (
        `UUID`,
        `GUID`,
        `AnarchyGovernor`,
        `EnvironmentType`,
        `CloudProvider`,
        `CloudRegion`,
        `UserName`,
        `UserEmail`,
        `ProvisionVars`
      ) VALUES (
        %s, %s, %s, %s, %s, %s, %s, %s, %s
      ) ON DUPLICATE KEY UPDATE
      `UserName` = %s,
      `UserEmail` = %s
