---
- name: Get ResourceClaim Data
  include_tasks: get-resource-claim-data.yaml
  when:
  - poolboy_resource_claim_name != ''
  - poolboy_resource_claim_namespace != ''

- name: Update GPTE Cost Reporting DB
  # Do not prevent provision when database is unavailable
  ignore_errors: "{{ gpte_reporting_ignore_errors | bool }}"
  mysql_query:
    login_db: "{{ gpte_db.mysql_db }}"
    login_host: "{{ gpte_db.mysql_host }}"
    login_port: "{{ gpte_db.mysql_port }}"
    login_password: "{{ gpte_db.mysql_password }}"
    login_user: "{{ gpte_db.mysql_user }}"

    positional_args:
    # INSERT
    - "{{ gpte_reporting_uuid }}"
    - "{{ gpte_reporting_guid }}"
    - "{{ vars.anarchy_subject.spec.governor }}"
    - "{{ gpte_reporting_env_type }}"
    - "{{ gpte_reporting_cloud_provider }}"
    - "{{ gpte_reporting_cloud_region }}"
    - "{{ request_guid }}" # RequestGUID - test and set
    - "{{ request_guid }}"
    - "{{ request_uuid }}" # RequestUUID - test and set
    - "{{ request_uuid }}"
    - "{{ request_uuid }}" # RequestDateTime - set to UTC_TIMESTAMP() if request_uuid value
    - "{{ gpte_reporting_user_name }}"
    - "{{ gpte_reporting_user_email }}"
    - "{{ gpte_reporting_job_vars | to_json }}"
    # ON DUPLICATE KEY UPDATE
    - "{{ request_guid }}" # RequestGUID - test and set
    - "{{ request_guid }}"
    - "{{ request_uuid }}" # RequestUUID - test and set
    - "{{ request_uuid }}"
    - "{{ request_uuid }}" # RequestDateTime - set to UTC_TIMESTAMP() if request_uuid value
    - "{{ gpte_reporting_user_name }}"
    - "{{ gpte_reporting_user_email }}"
    query:
    - |
      INSERT INTO Environments SET
        `UUID` = %s,
        `GUID` = %s,
        `AnarchyGovernor` = %s,
        `EnvironmentType` = %s,
        `CloudProvider` = %s,
        `CloudRegion` = %s,
        `RequestGUID` = IF(%s = '', NULL, %s),
        `RequestUUID` = IF(%s = '', NULL, %s),
        `RequestDateTime` = IF(%s = '', NULL, UTC_TIMESTAMP()),
        `UserName` = %s,
        `UserEmail` = %s,
        `ProvisionVars` = %s
      ON DUPLICATE KEY UPDATE
        `RequestGUID` = IFNULL(`RequestGUID`, IF(%s = '', NULL, %s)),
        `RequestUUID` = IFNULL(`RequestUUID`, IF(%s = '', NULL, %s)),
        `RequestDateTime` = IFNULL(`RequestDateTime`, IF(%s = '', NULL, UTC_TIMESTAMP())),
        `UserName` = %s,
        `UserEmail` = %s
