---
- name: Handle action/event
  vars:
    __tasks_file: >-
      {%- if anarchy_action_config_name is defined -%}
      {%-   if anarchy_action_callback_name is defined -%}
      handle-action-{{ anarchy_action_config_name }}-{{ anarchy_action_callback_name }}.yaml
      {%-   else -%}
      handle-action-{{ anarchy_action_config_name }}.yaml
      {%-   endif -%}
      {%- elif anarchy_event_name is defined -%}
      handle-event-{{ anarchy_event_name }}.yaml
      {%- else -%}
      handle-no-action-or-event.yaml
      {%- endif -%}
  when:
  - gpte_db is defined
  - gpte_reporting_uuid != ''
  - (role_path ~ '/tasks/' ~ __tasks_file) is file
  block:
  - name: Run pre-checks
    include_tasks: pre_checks.yaml

  - name: Run handler tasks for action/event
    include_tasks:
      file: "{{ __tasks_file }}"
