---
- debug:
    var: _info

  # Don't fail in case of undefined variables
  ignore_errors: true

  vars:
    _info:
      anarchy_action_config_name: "{{ anarchy_action_config_name | default('') }}"
      anarchy_action_callback_name: "{{ anarchy_action_callback_name | default('') }}"
      guid: "{{ gpte_reporting.guid }}"
      env_type: "{{ gpte_reporting.env_type }}"
      uuid: "{{ gpte_reporting.uuid }}"

- include_tasks: pre_checks.yaml

- include_tasks: db_init.yaml

- name: Report to provision DB
  when:
    - gpte_db is defined
    - anarchy_action_config_name is defined
    - anarchy_action_config_name == 'provision'
    - anarchy_action_callback_name is defined
    - anarchy_action_callback_name in ['started', 'complete']

  include_tasks: mysql.yaml
