---
- name: Insert info into GPTE LMS DB
  environment:
    MYSQL_TCP_PORT: "{{ gpte_reporting.mysql_port }}"
    MYSQL_HOST: "{{ gpte_reporting.mysql_host }}"
    MYSQL_PWD: "{{ gpte_reporting.mysql_password }}"

  # Do not fail the deployment if the DB is unreachable
  ignore_errors: true

  command: >-
    mysql -u "{{ gpte_reporting.mysql_user }}" "{{ gpte_reporting.mysql_db }}"

  # mysql -h qa-sfo00.opentlc.com -u provision_writer  <<< "describe lms_transactional.Provisions"
  # +------------------+--------------+------+-----+---------+-------+
  # | Field            | Type         | Null | Key | Default | Extra |
  # +------------------+--------------+------+-----+---------+-------+
  # | ProvisionDate    | datetime     | NO   |     | NULL    |       |
  # | UserName         | varchar(200) | NO   |     | NULL    |       |
  # | CatalogItem      | varchar(200) | NO   |     | NULL    |       |
  # | Partner          | varchar(200) | YES  |     | NULL    |       |
  # | Blueprint        | varchar(200) | YES  |     | NULL    |       |
  # | ClassName        | varchar(200) | YES  |     | NULL    |       |
  # | FullName         | varchar(200) | YES  |     | NULL    |       |
  # | Email            | varchar(200) | YES  |     | NULL    |       |
  # | Geo              | varchar(20)  | YES  |     | NULL    |       |
  # | ApplicationID    | varchar(100) | YES  |     | NULL    |       |
  # | StackID          | varchar(100) | YES  |     | NULL    |       |
  # | CostBucket       | varchar(50)  | YES  |     | NULL    |       |
  # | HourlyCostText   | varchar(50)  | YES  |     | NULL    |       |
  # | TotalCostText    | varchar(50)  | YES  |     | NULL    |       |
  # | WorkshopUsers    | varchar(50)  | YES  |     | NULL    |       |
  # | StudentWorkloads | varchar(50)  | YES  |     | NULL    |       |
  # | CloudService     | varchar(50)  | YES  |     | NULL    |       |
  # | GUID             | varchar(50)  | YES  |     | NULL    |       |
  # | UUID             | varchar(50)  | YES  |     | NULL    |       |
  # | ProvisionResult  | varchar(50)  | YES  |     | NULL    |       |
  # | DataSource       | varchar(50)  | YES  |     | NULL    |       |
  # | Catalog          | varchar(200) | YES  |     | NULL    |       |
  # | Opportunity      | varchar(200) | YES  |     | NULL    |       |
  # | Account          | varchar(200) | YES  |     | NULL    |       |
  # | Sandbox          | varchar(200) | YES  |     | NULL    |       |
  # +------------------+--------------+------+-----+---------+-------+

  args:
    stdin: >-
      INSERT INTO lms_transactional.Provisions
      (
      ProvisionDate,
      UserName,
      CatalogItem,
      Partner,
      FullName,
      Email,
      Geo,
      CloudService,
      GUID,
      UUID,
      ProvisionResult,
      DataSource
      )

      VALUES (
      (select now()),
      '{{ gpte_reporting.student_name | regex_replace("'", "") }}',
      '{{ gpte_reporting.catalog_name | regex_replace("'", "") }}',
      'redhat',
      'Babylon',
      '{{ gpte_reporting.email | regex_replace("'", "") }}',
      '{{ gpte_reporting.aws_region | regex_replace("'", "") }}',
      '{{ gpte_reporting.cloud_provider | regex_replace("'", "") }}',
      '{{ gpte_reporting.guid | regex_replace("'", "") }}',
      '{{ gpte_reporting.uuid | regex_replace("'", "") }}',
      'Success',
      'BABYLON'
      );
