---
- name: Test access with a simple query
  mysql_query:
    login_db: "{{ gpte_reporting.mysql_db }}"
    login_host: "{{ gpte_reporting.mysql_host }}"
    login_port: "{{ gpte_reporting.mysql_port }}"
    login_password: "{{ gpte_reporting.mysql_password }}"
    login_user: "{{ gpte_reporting.mysql_user }}"

    query:
      - SELECT 1

  ignore_errors: true
  register: r_select

- when: r_select is succeeded
  block:
  - name: Initialize Database
    include_tasks: db_init.yaml

  - name: Process provision {{ anarchy_action_callback_name }}
    include_tasks: handle-action-provision-{{ anarchy_action_callback_name }}.yaml
