---
- name: Test access with a simple query
  mysql_query:
    login_db: "{{ gpte_reporting.mysql_db }}"
    login_host: "{{ gpte_reporting.mysql_host }}"
    login_port: "{{ gpte_reporting.mysql_port }}"
    login_password: "{{ gpte_reporting.mysql_password }}"
    login_user: "{{ gpte_reporting.mysql_user }}"

    query:
      - SELECT 1

  ignore_errors: true
  register: r_select

# Deployment Started
- when:
    - r_select is succeeded
    - anarchy_action_callback_name == 'started'

  name: Insert info into GPTE LMS DB

  # mysql -h qa-sfo00.opentlc.com -u provision_writer  <<< "describe lms_transactional.Provisions"
  # +------------------+--------------+------+-----+---------+-------+
  # | Field            | Type         | Null | Key | Default | Extra |
  # +------------------+--------------+------+-----+---------+-------+
  # | ProvisionDate    | datetime     | NO   |     | NULL    |       |
  # | UserName         | varchar(200) | NO   |     | NULL    |       |
  # | CatalogItem      | varchar(200) | NO   |     | NULL    |       |
  # | Partner          | varchar(200) | YES  |     | NULL    |       |
  # | Blueprint        | varchar(200) | YES  |     | NULL    |       |
  # | ClassName        | varchar(200) | YES  |     | NULL    |       |
  # | FullName         | varchar(200) | YES  |     | NULL    |       |
  # | Email            | varchar(200) | YES  |     | NULL    |       |
  # | Geo              | varchar(20)  | YES  |     | NULL    |       |
  # | ApplicationID    | varchar(100) | YES  |     | NULL    |       |
  # | StackID          | varchar(100) | YES  |     | NULL    |       |
  # | CostBucket       | varchar(50)  | YES  |     | NULL    |       |
  # | HourlyCostText   | varchar(50)  | YES  |     | NULL    |       |
  # | TotalCostText    | varchar(50)  | YES  |     | NULL    |       |
  # | WorkshopUsers    | varchar(50)  | YES  |     | NULL    |       |
  # | StudentWorkloads | varchar(50)  | YES  |     | NULL    |       |
  # | CloudService     | varchar(50)  | YES  |     | NULL    |       |
  # | GUID             | varchar(50)  | YES  |     | NULL    |       |
  # | UUID             | varchar(50)  | YES  |     | NULL    |       |
  # | ProvisionResult  | varchar(50)  | YES  |     | NULL    |       |
  # | DataSource       | varchar(50)  | YES  |     | NULL    |       |
  # | Catalog          | varchar(200) | YES  |     | NULL    |       |
  # | Opportunity      | varchar(200) | YES  |     | NULL    |       |
  # | Account          | varchar(200) | YES  |     | NULL    |       |
  # | Sandbox          | varchar(200) | YES  |     | NULL    |       |
  # +------------------+--------------+------+-----+---------+-------+
  # Do not fail the deployment if the DB is unreachable
  ignore_errors: true
  mysql_query:
    login_db: "{{ gpte_reporting.mysql_db }}"
    login_host: "{{ gpte_reporting.mysql_host }}"
    login_port: "{{ gpte_reporting.mysql_port }}"
    login_password: "{{ gpte_reporting.mysql_password }}"
    login_user: "{{ gpte_reporting.mysql_user }}"

    positional_args:
      - "{{ gpte_reporting.student_name }}"
      - "{{ gpte_reporting.catalog_item }}"
      - "{{ gpte_reporting.email }}"
      - "{{ gpte_reporting.aws_region }}"
      - "{{ gpte_reporting.cloud_provider }}"
      - "{{ gpte_reporting.guid }}"
      - "{{ gpte_reporting.uuid }}"

    query:
      - >-
        INSERT INTO lms_transactional.Provisions
        ( ProvisionDate,
          UserName,
          CatalogItem,
          Partner,
          FullName,
          Email,
          Geo,
          CloudService,
          GUID,
          UUID,
          ProvisionResult,
          DataSource )

        VALUES (
          (select now()),
          %s,
          %s,
          'redhat',
          'Babylon',
          %s,
          %s,
          %s,
          %s,
          %s,
          'Started',
          'BABYLON'
        );

- when:
    - r_select is succeeded
    - anarchy_action_callback_name == 'complete'

  name: Update Provision status in GPTE LMS DB

  ignore_errors: true
  mysql_query:
    login_db: "{{ gpte_reporting.mysql_db }}"
    login_host: "{{ gpte_reporting.mysql_host }}"
    login_port: "{{ gpte_reporting.mysql_port }}"
    login_password: "{{ gpte_reporting.mysql_password }}"
    login_user: "{{ gpte_reporting.mysql_user }}"

    positional_args:
      - "{{ gpte_reporting.uuid }}"
      - "{{ gpte_reporting.guid }}"

    query:
      - >-
        UPDATE lms_transactional.Provisions SET ProvisionResult = 'Success'
        WHERE uuid = %s
        AND guid = %s
        AND DataSource = 'BABYLON';
